version: '3'

networks:
  frontend:
    external:
      name: ananas-erp

services:
  frontend:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - "..:/workspace"
    networks:
    - frontend

